#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub(crate) enum SignalId {
    RuntimeCommandQueued,
    RuntimeQueueDepthTotal,
    RuntimeCommandProcessed,
    RuntimeNotifyRequested,
    RuntimeRedrawRequested,
    RuntimeRedrawCoalesced,
    RuntimeStaleDrop,
    ApiEntityCreated,
    ApiEntityRead,
    ApiEntityUpdate,
    ApiEntityNotify,
    ApiEntityNotificationFlushed,
    ApiHandleStale,
    ApiSubscriptionCancelled,
    RetainedDiff,
    RetainedNodesTotal,
    RetainedNodesCreated,
    RetainedNodesPreserved,
    RetainedNodesReplaced,
    RetainedNodesDestroyed,
    RetainedKindMismatch,
    RetainedDuplicateKey,
    RetainedNodeCreated,
    RetainedDirty,
    RetainedNodeDestroyed,
    StyleNodesResolved,
    StyleResolve,
    LayoutPass,
    LayoutNodesTotal,
    LayoutGeometryChanged,
    LayoutMeasureText,
    LayoutMeasureTextCacheHit,
    LayoutMeasureTextCacheMiss,
    LayoutBlockedOnText,
    LayoutDefer,
    TextMeasure,
    TextMeasureCacheHit,
    TextMeasureCacheMiss,
    TextMeasureDeferred,
    TextMeasureFailed,
    TextMeasureDurationMicros,
    SceneCompile,
    SceneFragmentCount,
    SceneDamage,
    SceneResourceDemand,
    SceneStaleDrop,
    InputPointerFact,
    InputHit,
    InputMiss,
    InputDispatch,
    InputClickDerived,
    InputStaleTarget,
}

impl SignalId {
    pub(crate) const COUNT: usize = 52;

    pub(crate) const ALL: [Self; Self::COUNT] = [
        Self::RuntimeCommandQueued,
        Self::RuntimeQueueDepthTotal,
        Self::RuntimeCommandProcessed,
        Self::RuntimeNotifyRequested,
        Self::RuntimeRedrawRequested,
        Self::RuntimeRedrawCoalesced,
        Self::RuntimeStaleDrop,
        Self::ApiEntityCreated,
        Self::ApiEntityRead,
        Self::ApiEntityUpdate,
        Self::ApiEntityNotify,
        Self::ApiEntityNotificationFlushed,
        Self::ApiHandleStale,
        Self::ApiSubscriptionCancelled,
        Self::RetainedDiff,
        Self::RetainedNodesTotal,
        Self::RetainedNodesCreated,
        Self::RetainedNodesPreserved,
        Self::RetainedNodesReplaced,
        Self::RetainedNodesDestroyed,
        Self::RetainedKindMismatch,
        Self::RetainedDuplicateKey,
        Self::RetainedNodeCreated,
        Self::RetainedDirty,
        Self::RetainedNodeDestroyed,
        Self::StyleNodesResolved,
        Self::StyleResolve,
        Self::LayoutPass,
        Self::LayoutNodesTotal,
        Self::LayoutGeometryChanged,
        Self::LayoutMeasureText,
        Self::LayoutMeasureTextCacheHit,
        Self::LayoutMeasureTextCacheMiss,
        Self::LayoutBlockedOnText,
        Self::LayoutDefer,
        Self::TextMeasure,
        Self::TextMeasureCacheHit,
        Self::TextMeasureCacheMiss,
        Self::TextMeasureDeferred,
        Self::TextMeasureFailed,
        Self::TextMeasureDurationMicros,
        Self::SceneCompile,
        Self::SceneFragmentCount,
        Self::SceneDamage,
        Self::SceneResourceDemand,
        Self::SceneStaleDrop,
        Self::InputPointerFact,
        Self::InputHit,
        Self::InputMiss,
        Self::InputDispatch,
        Self::InputClickDerived,
        Self::InputStaleTarget,
    ];

    pub(crate) const fn name(self) -> &'static str {
        match self {
            Self::RuntimeCommandQueued => "runtime.command_queued",
            Self::RuntimeQueueDepthTotal => "runtime.queue_depth_total",
            Self::RuntimeCommandProcessed => "runtime.command_processed",
            Self::RuntimeNotifyRequested => "runtime.notify_requested",
            Self::RuntimeRedrawRequested => "runtime.redraw_requested",
            Self::RuntimeRedrawCoalesced => "runtime.redraw_coalesced",
            Self::RuntimeStaleDrop => "runtime.stale_drop",
            Self::ApiEntityCreated => "api.entity.created",
            Self::ApiEntityRead => "api.entity.read",
            Self::ApiEntityUpdate => "api.entity.update",
            Self::ApiEntityNotify => "api.entity.notify",
            Self::ApiEntityNotificationFlushed => "api.entity.notification_flushed",
            Self::ApiHandleStale => "api.handle.stale",
            Self::ApiSubscriptionCancelled => "api.subscription.cancelled",
            Self::RetainedDiff => "retained.diff",
            Self::RetainedNodesTotal => "retained.nodes_total",
            Self::RetainedNodesCreated => "retained.nodes_created",
            Self::RetainedNodesPreserved => "retained.nodes_preserved",
            Self::RetainedNodesReplaced => "retained.nodes_replaced",
            Self::RetainedNodesDestroyed => "retained.nodes_destroyed",
            Self::RetainedKindMismatch => "retained.kind_mismatch",
            Self::RetainedDuplicateKey => "retained.duplicate_key",
            Self::RetainedNodeCreated => "retained.node_created",
            Self::RetainedDirty => "retained.dirty",
            Self::RetainedNodeDestroyed => "retained.node_destroyed",
            Self::StyleNodesResolved => "style.nodes_resolved",
            Self::StyleResolve => "style.resolve",
            Self::LayoutPass => "layout.pass",
            Self::LayoutNodesTotal => "layout.nodes_total",
            Self::LayoutGeometryChanged => "layout.geometry_changed",
            Self::LayoutMeasureText => "layout.measure_text",
            Self::LayoutMeasureTextCacheHit => "layout.measure_text.cache_hit",
            Self::LayoutMeasureTextCacheMiss => "layout.measure_text.cache_miss",
            Self::LayoutBlockedOnText => "layout.blocked_on_text",
            Self::LayoutDefer => "layout.defer",
            Self::TextMeasure => "text.measure",
            Self::TextMeasureCacheHit => "text.measure.cache_hit",
            Self::TextMeasureCacheMiss => "text.measure.cache_miss",
            Self::TextMeasureDeferred => "text.measure.deferred",
            Self::TextMeasureFailed => "text.measure.failed",
            Self::TextMeasureDurationMicros => "text.measure.duration_micros",
            Self::SceneCompile => "scene.compile",
            Self::SceneFragmentCount => "scene.fragment_count",
            Self::SceneDamage => "scene.damage",
            Self::SceneResourceDemand => "scene.resource_demand",
            Self::SceneStaleDrop => "scene.stale_drop",
            Self::InputPointerFact => "input.pointer_fact",
            Self::InputHit => "input.hit",
            Self::InputMiss => "input.miss",
            Self::InputDispatch => "input.dispatch",
            Self::InputClickDerived => "input.click_derived",
            Self::InputStaleTarget => "input.stale_target",
        }
    }

    pub(crate) const fn index(self) -> usize {
        self as usize
    }

    pub(crate) fn from_name(name: &'static str) -> Option<Self> {
        Self::ALL.into_iter().find(|signal| signal.name() == name)
    }
}
